### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by antoniobenedetti** [cuberite/ProtectionAreas#6] opened 2014-02-03 13:16 UTC
```
[14:12:37] LUA: Plugins/ProtectionAreas/HookHandlers.lua:26: attempt to index local 'a_Player' (a nil value)
[14:12:44] Stack trace:
[14:12:44]   [C](-1): (no name)
[14:12:44]   Plugins/ProtectionAreas/HookHandlers.lua(26): (no name)
[14:12:44] Stack trace end
[14:12:44] Error in plugin ProtectionAreas calling function <callback>()
[14:13:22]   D:    | MCServer has encountered an error and needs to close
[14:13:23] Details | SIGABRT: Server self-terminated due to an internal fault
[14:13:24] Shutting down server...
[14:13:24] Shutting down server...
```

**Comment by williamhatcher** [comment] 2017-08-18 07:40
I was not able to reproduce this on the current version of Cuberite and ProtectionAreas. Can we close this issue?

**Comment by bearbin** [comment] 2017-08-21 08:08
Closing, no updates for 2 years.

**Closed by bearbin** 2017-08-21 08:08 UTC
